#!/usr/bin/env bash

#remove generated keys and ssh configurations
rm -f ~user/id_rsa*
rm -f ~user/.ssh/*

rm -f ~root/id_rsa*
rm -f ~root/.ssh/*

#revert default configurations for SNMP and syslog
tar -C / --overwrite -xf /root/isa5/defaults.tar

#shutdown SNMP and syslog
systemctl stop snmpd.service
systemctl stop rsyslog.service

shutdown -h now
