#!/usr/bin/env bash

rm /etc/dhcp/* &> /dev/null
rm /etc/radvd.conf &> /dev/null
rm /etc/*reso* &> /dev/null
rm /etc/name/* &> /dev/null
rm /var/named/* &> /dev/null
rm /home/user/.ssh/* &> /dev/null

tar -C / --overwrite -xf /root/isa3/default.tar

#service networking restart &> /dev/null
#service isc-dhcp-server restart &> /dev/null
#service bind9 restart &> /dev/null

systemctl restart network.service
systemctl stop named.service

dhclient enp2s0 &> /dev/null

shutdown -h now
