#!/usr/bin/env bash

rm /etc/dhcp/* &> /dev/null
rm /etc/radvd.conf &> /dev/null
rm /etc/*reso* &> /dev/null
rm /etc/name/* &> /dev/null
rm /etc/dhcp/dhclient-enp2s0.conf &> /dev/null
rm /var/named/* &> /dev/null
rm /home/user/.ssh/* &> /dev/null
rm /home/root/.ssh/* &> /dev/null

chmod -R 0755 /root/isa3/
tar -C / --overwrite -xf /root/isa3/default.tar
chmod -R 0444 /root/isa3/
chmod 0544 /root/isa3/clean

#service networking restart &> /dev/null
#service isc-dhcp-server restart &> /dev/null
#service bind9 restart &> /dev/null

systemctl restart network.service
systemctl stop named.service

sed -i '/^PEERDNS/d/g' /etc/sysconfig/network-scripts/ifcfg-Wired_connection_1
sed -i '/^DNS/d/g' /etc/sysconfig/network-scripts/ifcfg-Wired_connection_1

shutdown -h now
