#!/usr/bin/env bash

rm /etc/dhcp/* &> /dev/null
rm /etc/radvd.conf &> /dev/null
rm /etc/*reso* &> /dev/null

ip addr flush dev eth0
ip addr flush dev eth1

tar -C / --overwrite -xf /root/isa1/default.tar

systemctl enable NetworkManager.service
systemctl disable isc-dhcp-server.service
systemctl disable radvd.service

dhclient eth0 &> /dev/null

shutdown -h now
