all: cv1.pdf

cv1.dvi: cv1.tex lab1-arch.tex Makefile
	latex $<
	latex $<
	latex $<

%.ps: %.dvi
	dvips -f -t a4 $< > $@

%.pdf: %.ps
	ps2pdf14 -sPAPERSIZE=letter $<

clean:
	rm *.aux *.dvi *.log *.blg
