#!/bin/bash

if [ "$EUID" -ne 0 ]
  then echo "You run me as a user. Please run me again as a root!"
  exit
fi

yum remove unbound -y

printf "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4\n::1         localhost localhost.localdomain localhost6 localhost6.localdomain6\n\n" > /etc/hosts

printf "# Generated by NetworkManager\nsearch netlab.fit.vutbr.cz\nnameserver 10.10.10.1\n\n" > /etc/resolv.conf

echo "OK. I am rebooting..."

reboot

